### ISSUE TITLE
OpenCV AI Competition 2021

### ISSUE THREAD

**Issue by matanster** [geaxgx/depthai_hand_tracker#1]
Dear @geaxgx,

Not really an issue, but I signed up for the 2021 competition, and stumbled here when looking around for ways to accomplish DepthAI integration with MediaPipe.

Then the Github user looked familiar :-) 

I was accepted to stage 1 of the 2021 cycle, with a proposal that integrates voice, dynamic gesture and learning from feedback for human-machine-interaction. Would be happy to get in touch. 

matan@copula.ai

**Comment by geaxgx** [comment]
I sent you an email.

**Comment by matanster** [comment]
Thanks for your kind response. If you change your mind ...
