### ISSUE TITLE
Compatibility with Unity

### ISSUE THREAD

**Issue by Telepresent** [geaxgx/depthai_hand_tracker#11]
Hi, 

I would like to request if it would be possible to get this hand tracking functionality for Unity/Unreal Engine virtual reality environments. 

It would also be interesting to be able to work with physical objects: https://www.youbionic.com/

**Comment by geaxgx** [comment]
I am not familiar with Unity or Unreal engine but it is something I would like to learn and implement when I will have time. 
In the meantime, Luxonis is already working on the integration of depthai with Unity. In the roadmap  https://github.com/luxonis/depthai-unity/issues/1 , you can see that hand tracking is already planned.

The bionic hand looks very cool!

**Comment by gespona** [comment]
> I am not familiar with Unity or Unreal engine but it is something I would like to learn and implement when I will have time. In the meantime, Luxonis is already working on the integration of depthai with Unity. In the roadmap [luxonis/depthai-unity#1](https://github.com/luxonis/depthai-unity/issues/1) , you can see that hand tracking is already planned.
> 
> The bionic hand looks very cool!

Hi ! Just want to confirm we're working on hand tracking Unity integration inside the DepthAI Unity Plugin (OAK For Unity). You can see initial work here:
https://youtu.be/NddeLxUBOTg

**Comment by geaxgx** [comment]
Closing as stale. Please reopen if you'd like to work on this further.
