### ISSUE TITLE
Demos doesn't work

### ISSUE THREAD

**Issue by Quantum-0** [geaxgx/depthai_hand_tracker#14]
Commit: c803ad33437637d06c25fd44e5c3ef7c8760ff1e
Python 3.10.0
depthai==2.14.1.0
Windows, Laptop with camera

Log:
```
> python demo.py
Palm detection blob : C:\Users\Quantum\PycharmProjects\depthai_hand_tracker\models\palm_detection_sh4.blob
Landmark blob       : C:\Users\Quantum\PycharmProjects\depthai_hand_tracker\models\hand_landmark_lite_sh4.blob
Traceback (most recent call last):
  File "C:\Users\Quantum\PycharmProjects\depthai_hand_tracker\demo.py", line 59, in <module>
    tracker = HandTracker(
  File "C:\Users\Quantum\PycharmProjects\depthai_hand_tracker\HandTracker.py", line 130, in __init__
    self.device = dai.Device()
RuntimeError: No available devices
```

What I'm doing wrong?

**Comment by geaxgx** [comment]
Hi, this repository works only with  Luxonis DepthAI hardware (OAK-D, OAK-D lite, OAK-1,... https://docs.luxonis.com/projects/hardware/en/latest/) and not with usual webcam.

**Comment by Anton-Velikodnyy** [comment]
@geaxgx 
Iinput say can be image. Quick look at code shows trying load device at start with image/video specified with -i

**Comment by Anton-Velikodnyy** [comment]
see [linked line](https://github.com/geaxgx/depthai_hand_tracker/blob/87111c1c454bb9d3c936f19fe752605b0ca32c37/HandTracker.py#L130), does not seem to have a way without device already linked. I dont have device but this repo suggest it can run on mp4 or image.

**Comment by geaxgx** [comment]
@Anton-Velikodnyy Even if you use an image or a video as input, you still need an OAK* device to run the neural networks on the device's MyriadX.
