### ISSUE TITLE
Manually specify device IP

### ISSUE THREAD

**Issue by AlecMulder** [geaxgx/depthai_hand_tracker#17]
I have 3 OAK-D PoE cameras on the same network and am unable to specify an IP address to ensure the correct device is being used. 

I tried following the guide [here](https://docs.luxonis.com/projects/hardware/en/latest/pages/guides/getting-started-with-poe.html#manually-specify-device-ip) but I ran into issues adding parameters to the initialization. It requires the pipeline but it isn't created yet and my python skills aren't up to the task. 

Am I on the right track or is there a better way to accomplish this?

**Comment by geaxgx** [comment]
I don't have a PoE camera so I can't test.
Have you tried to replace https://github.com/geaxgx/depthai_hand_tracker/blob/87111c1c454bb9d3c936f19fe752605b0ca32c37/HandTracker.py#L130
with: 
```
device_info = dai.DeviceInfo()
device_info.state = dai.XLinkDeviceState.X_LINK_BOOTLOADER
device_info.desc.protocol = dai.XLinkProtocol.X_LINK_TCP_IP
device_info.desc.name = "169.254.1.222"
self.device = dai.Device(devInfo=device_info)
```

Here I am modifying HandTracker.py. For the edge mode, I would similarly modify HandTrackerEdge.py.
If it does not work, I would suggest you contect Luxonis support. They will be able to help you.

**Comment by geaxgx** [comment]
Closing as stale. Please reopen if you'd like to work on this further.
