### ISSUE TITLE
Cant read Landmark blob,Can read Plam blob

### ISSUE THREAD

**Issue by Cursky** [geaxgx/depthai_hand_tracker#18]
(oak) PS D:\OAK\depthai_hand_tracker-main> python ./demo.py
Palm detection blob : D:\OAK\depthai_hand_tracker-main\models\palm_detection_sh4.blob
Landmark blob       : D:\OAK\depthai_hand_tracker-main\models\hand_landmark_lite_sh4.blob
Internal camera FPS set to: 23
Sensor resolution: (1920, 1080)
Internal camera image size: 1152 x 648 - crop_w:0 pad_h: 252
896 anchors have been created
Creating pipeline...
Creating Color Camera...
Creating Palm Detection Neural Network...
Creating Hand Landmark Neural Network (2 threads)...
Pipeline created.
Stack trace (most recent call last):
#31   Object "", at 00007FFD557F3BA9, in PyObject_MakeTpCall
#30   Object "", at 00007FFD557F7046, in PyArg_CheckPositional
#29   Object "", at 00007FFD44BAA382, in pybind11::error_already_set::error_already_set
#28   Object "", at 00007FFD44BE9814, in PyInit_depthai
#27   Object "", at 00007FFD44BE976E, in PyInit_depthai
#26   Object "", at 00007FFD44DB8619, in PyInit_depthai
#25   Object "", at 00007FFD44DB28F5, in PyInit_depthai
#24   Object "", at 00007FFD44D8B89D, in PyInit_depthai
#23   Object "", at 00007FFD44D9B3B1, in PyInit_depthai
#22   Object "", at 00007FFD44D9AAF5, in PyInit_depthai
#21   Object "", at 00007FFD44E2261B, in PyInit_depthai
#20   Object "", at 00007FFD44E227AF, in PyInit_depthai
#19   Object "", at 00007FFD44EA5CFC, in PyInit_depthai
#18   Object "", at 00007FFDD248474C, in RaiseException
#17   Object "", at 00007FFDD4CD3163, in RtlRaiseException
#16   Object "", at 00007FFDD4CD5E9A, in RtlRestoreContext
#15   Object "", at 00007FFDD4D48FCF, in _chkstk
#14   Object "", at 00007FFD44EA3BBC, in PyInit_depthai
#13   Object "", at 00007FFD44EA5061, in PyInit_depthai
#12   Object "", at 00007FFD44EA8E68, in PyInit_depthai
#11   Object "", at 00007FFD44EA80BF, in PyInit_depthai
#10   Object "", at 00007FFD44EA7845, in PyInit_depthai
#9    Object "", at 00007FFD44EA4C6E, in PyInit_depthai
#8    Object "", at 00007FFDD4CD8E63, in RtlUnwindEx
#7    Object "", at 00007FFDD4D4904F, in _chkstk
#6    Object "", at 00007FFD44EA3BBC, in PyInit_depthai
#5    Object "", at 00007FFD44EA5061, in PyInit_depthai
#4    Object "", at 00007FFD44EA8D95, in PyInit_depthai
#3    Object "", at 00007FFD44EA46BD, in PyInit_depthai
#2    Object "", at 00007FFD44EA9A81, in PyInit_depthai
#1    Object "", at 00007FFD44EB217A, in PyInit_depthai
#0    Object "", at 00007FFD44D99A34, in PyInit_depthai

**Comment by Cursky** [comment]
i run python demo.py cant read landmark blob model,i use OAK-D-Lite Carmer,but successful when i run python demo.py --no_lm. Could u help me ? thank u

**Comment by geaxgx** [comment]
First time I see an error like this.
Does it crash as soon as you run the script, or after a while ?
Do you have  the last depthai version 2.17.3 ?
In edge mode (`./demo.py -e`) do you get the same error ?
Can you change the debugging level before running the command:
```
set DEPTHAI_LEVEL=debug
./demo.py
```
then send me the trace ?

**Comment by Cursky** [comment]
After I ran the script, it crashed immediately，Occasionally, it can run successfully。But in most cases, it ended in failure
my env is win11 ;deepai 2.17.3;

**Comment by Cursky** [comment]
(oak) PS D:\OAK\depthai_hand_tracker-main> set DEPTHAI_LEVEL=debug
(oak) PS D:\OAK\depthai_hand_tracker-main> python .\demo.py
Palm detection blob : D:\OAK\depthai_hand_tracker-main\models\palm_detection_sh4.blob
Landmark blob       : D:\OAK\depthai_hand_tracker-main\models\hand_landmark_lite_sh4.blob
Internal camera FPS set to: 23
Sensor resolution: (1920, 1080)
Internal camera image size: 1152 x 648 - crop_w:0 pad_h: 252
896 anchors have been created
Creating pipeline...
Creating Color Camera...
Creating Palm Detection Neural Network...
Creating Hand Landmark Neural Network (2 threads)...
Pipeline created.
Stack trace (most recent call last):
#31   Object "", at 00007FFBB4183BA9, in PyObject_MakeTpCall
#30   Object "", at 00007FFBB4187046, in PyArg_CheckPositional
#29   Object "", at 00007FFBB051A382, in pybind11::error_already_set::error_already_set
#28   Object "", at 00007FFBB0559814, in PyInit_depthai
#27   Object "", at 00007FFBB055976E, in PyInit_depthai
#26   Object "", at 00007FFBB0728619, in PyInit_depthai
#25   Object "", at 00007FFBB07228F5, in PyInit_depthai
#24   Object "", at 00007FFBB06FB89D, in PyInit_depthai
#23   Object "", at 00007FFBB070B3B1, in PyInit_depthai
#22   Object "", at 00007FFBB070AAF5, in PyInit_depthai
#21   Object "", at 00007FFBB079261B, in PyInit_depthai
#20   Object "", at 00007FFBB07927AF, in PyInit_depthai
#19   Object "", at 00007FFBB0815CFC, in PyInit_depthai
#18   Object "", at 00007FFC4A86474C, in RaiseException
#17   Object "", at 00007FFC4D253163, in RtlRaiseException
#16   Object "", at 00007FFC4D255E9A, in RtlRestoreContext
#15   Object "", at 00007FFC4D2C8FCF, in _chkstk
#14   Object "", at 00007FFBB0813BBC, in PyInit_depthai
#13   Object "", at 00007FFBB0815061, in PyInit_depthai
#12   Object "", at 00007FFBB0818E68, in PyInit_depthai
#11   Object "", at 00007FFBB08180BF, in PyInit_depthai
#10   Object "", at 00007FFBB0817845, in PyInit_depthai
#9    Object "", at 00007FFBB0814C6E, in PyInit_depthai
#8    Object "", at 00007FFC4D258E63, in RtlUnwindEx
#7    Object "", at 00007FFC4D2C904F, in _chkstk
#6    Object "", at 00007FFBB0813BBC, in PyInit_depthai
#5    Object "", at 00007FFBB0815061, in PyInit_depthai
#4    Object "", at 00007FFBB0818D95, in PyInit_depthai
#3    Object "", at 00007FFBB08146BD, in PyInit_depthai
#2    Object "", at 00007FFBB0819A81, in PyInit_depthai
#1    Object "", at 00007FFBB082217A, in PyInit_depthai
#0    Object "", at 00007FFBB0709A34, in PyInit_depthai

**Comment by Cursky** [comment]
(oak) PS D:\OAK\depthai_hand_tracker-main> python .\demo.py -e
Palm detection blob     : D:\OAK\depthai_hand_tracker-main\models\palm_detection_sh4.blob
Landmark blob           : D:\OAK\depthai_hand_tracker-main\models\hand_landmark_lite_sh4.blob
PD post processing blob : D:\OAK\depthai_hand_tracker-main\custom_models\PDPostProcessing_top2_sh1.blob
Sensor resolution: (1920, 1080)
Internal camera FPS set to: 36
Internal camera image size: 1152 x 648 - pad_h: 252
Creating pipeline...
Creating Color Camera...
Creating Palm Detection pre processing image manip...
Creating Palm Detection Neural Network...
Creating Palm Detection post processing Neural Network...
Creating Hand Landmark pre processing image manip...
Creating Hand Landmark Neural Network (2 threads)...
Pipeline created.
Stack trace (most recent call last):
#31   Object "", at 00007FFBB4183BA9, in PyObject_MakeTpCall
#30   Object "", at 00007FFBB4187046, in PyArg_CheckPositional
#29   Object "", at 00007FFBB051A382, in pybind11::error_already_set::error_already_set
#28   Object "", at 00007FFBB0559814, in PyInit_depthai
#27   Object "", at 00007FFBB055976E, in PyInit_depthai
#26   Object "", at 00007FFBB0728619, in PyInit_depthai
#25   Object "", at 00007FFBB07228F5, in PyInit_depthai
#24   Object "", at 00007FFBB06FB89D, in PyInit_depthai
#23   Object "", at 00007FFBB070B3B1, in PyInit_depthai
#22   Object "", at 00007FFBB070AAF5, in PyInit_depthai
#21   Object "", at 00007FFBB079261B, in PyInit_depthai
#20   Object "", at 00007FFBB07927AF, in PyInit_depthai
#19   Object "", at 00007FFBB0815CFC, in PyInit_depthai
#18   Object "", at 00007FFC4A86474C, in RaiseException
#17   Object "", at 00007FFC4D253163, in RtlRaiseException
#16   Object "", at 00007FFC4D255E9A, in RtlRestoreContext
#15   Object "", at 00007FFC4D2C8FCF, in _chkstk
#14   Object "", at 00007FFBB0813BBC, in PyInit_depthai
#13   Object "", at 00007FFBB0815061, in PyInit_depthai
#12   Object "", at 00007FFBB0818E68, in PyInit_depthai
#11   Object "", at 00007FFBB08180BF, in PyInit_depthai
#10   Object "", at 00007FFBB0817845, in PyInit_depthai
#9    Object "", at 00007FFBB0814C6E, in PyInit_depthai
#8    Object "", at 00007FFC4D258E63, in RtlUnwindEx
#7    Object "", at 00007FFC4D2C904F, in _chkstk
#6    Object "", at 00007FFBB0813BBC, in PyInit_depthai
#5    Object "", at 00007FFBB0815061, in PyInit_depthai
#4    Object "", at 00007FFBB0818D95, in PyInit_depthai
#3    Object "", at 00007FFBB08146BD, in PyInit_depthai
#2    Object "", at 00007FFBB0819A81, in PyInit_depthai
#1    Object "", at 00007FFBB082217A, in PyInit_depthai
#0    Object "", at 00007FFBB0709A34, in PyInit_depthai

**Comment by geaxgx** [comment]
I have found there someone that has exactly the same problem as you: https://manumaruscript.com/oak-d-lite-pybind11error/ (using google translate may be necessary). It turns out that the problem was solved by changing the usb cable.
Hope it helps.

**Comment by Cursky** [comment]
Thank you for your reply. I also considered this issue yesterday. Now the courier is sending me a new usb3. After the test is successful, I will reply here. I wish you a happy life.Thank u.

**Comment by Cursky** [comment]
Using high transmission USB cable can solve this problem :)
