### ISSUE TITLE
Issues with numpy 1.24.1

### ISSUE THREAD

**Issue by DBraun** [geaxgx/depthai_hand_tracker#22]
https://numpy.org/devdocs/release/1.24.0-notes.html

`np.int` is no longer available, causing an issue with
https://github.com/geaxgx/depthai_hand_tracker/blob/87111c1c454bb9d3c936f19fe752605b0ca32c37/HandTrackerRenderer.py#L68
and
https://github.com/geaxgx/depthai_hand_tracker/blob/87111c1c454bb9d3c936f19fe752605b0ca32c37/HandTracker.py#L434

From what I can tell the solution is to use `np.int32`

**Comment by geaxgx** [comment]
Thanks a lot !
I have replaced occurences of `np.int` by `np.int32`.
