### ISSUE TITLE
Problem running with -xyz with OAK-D

### ISSUE THREAD

**Issue by SimonStHilaire** [geaxgx/depthai_hand_tracker#3]
Hi,

  first thank you for your work!

The demo works fine but I can't get it to work with -xyz with an OAK-D attached. Here's what I get:

File "demo.py", line 58, in <module>
    **tracker_args
  File "/home/pi/depthai-python/HandTracker.py", line 172, in __init__
    self.device.startPipeline(self.create_pipeline())
depthai.XLinkReadError: Couldn't read data from stream: '__rpc_main' (X_LINK_ERROR)

Somebody have an idea on what the problem might be?

Thanks

**Comment by geaxgx** [comment]
Hi, I don't see any obvious explanation to your problem.
Is it a problem with depthai version ? I am realizing that the "Install" chapter of the README has become obsolete: the develop branch is not needed anymore. You can just use the regular depthai version (e.g. 2.10).
Do you have the problem in Host mode (./demo.py -xyz) and in Edge mode (./demo.py -e -xyz) ?

**Comment by SimonStHilaire** [comment]
Hi,  tank you for the reply. The problem happens in both host and edge mode. I switched back to the main branch but no luck.
I noticed that I get the warning "Calibration Data on device is empty" . Just tried the "rgb_depth_aligned.py" example and I also get the warning an an error. It might be related. I can display the depth feed but maybe can't use it. I read that the calibration should be on the device from factory for recent models. Since I just bought it, I thought it was one, maybe not.

The error with rgb_depth_aligned is different but also related to the pipeline:

[14442C1041592CD700] [306.784] [system] [warning] Calibration Data on device is empty
Traceback (most recent call last):
  File "rgb_depth_aligned.py", line 60, in <module>
    with dai.Device(pipeline) as device:
RuntimeError: std::exception


I will try to do a calibration and try again. 


Here's the full execution log in case something pops out:

Palm detection blob file : /home/pi/depthai-python/models/palm_detection_sh4.blob
Landmark blob file : /home/pi/depthai-python/models/hand_landmark_sh4.blob
[14442C1041592CD700] [120.168] [system] [warning] Calibration Data on device is empty
Internal camera FPS set to: 28
Sensor resolution: (1920, 1080)
Internal camera image size: 1152 x 648 - crop_w:0 pad_h: 252
896 anchors have been created
Creating pipeline...
Creating Color Camera...
Creating letterboxing image manip...
Creating MonoCameras, Stereo and SpatialLocationCalculator nodes...
Creating Palm Detection Neural Network...
Creating Hand Landmark Neural Network...
Pipeline created.
Traceback (most recent call last):
  File "demo.py", line 58, in <module>
    **tracker_args
  File "/home/pi/depthai-python/HandTracker.py", line 172, in __init__
    self.device.startPipeline(self.create_pipeline())
RuntimeError: Couldn't read data from stream: '__rpc_main' (X_LINK_ERROR)

**Comment by geaxgx** [comment]
_> I read that the calibration should be on the device from factory for recent models._
Yes, it should be as you said.
I suggest you contact Luxonis support. 
On their discord (https://discord.com/invite/EPsZHkg9Nx), they are usually very reactive (you can use the #support channel).

**Comment by SimonStHilaire** [comment]
Thank you for your help.

**Comment by SimonStHilaire** [comment]
Hi, since I didn't bought it from Luxonis, it was not calibrated. After a manual calibration it is now working fine. Thans again,
