### ISSUE TITLE
Requirement Installation

### ISSUE THREAD

**Issue by seahcj** [geaxgx/depthai_hand_tracker#4]
Error during  requirement installation in Windows 10, python 3.9.1

`(venv) PS D:\_ai\depthai_hand_tracker> pip.exe install -r .\requirements.txt
Looking in indexes: https://pypi.org/simple, https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local/
ERROR: Could not find a version that satisfies the requirement open3d
ERROR: No matching distribution found for open3d`

Change requirements.txt, from 'open3d' to 'open3d-python'

**Comment by geaxgx** [comment]
Hi,
It seems that for python 3.9, you need the development version of open3d: http://www.open3d.org/docs/latest/getting_started.html#development-version-pip

What versions of open3d do you get when using  'open3d-python' ?
